export const content: string;
export const hContent: string;
export const hRoot: string;
export const hScrollbar: string;
export const root: string;
export const scrollbar: string;
export const vContent: string;
export const vRoot: string;
export const vScrollbar: string;
