export const root: string;
export const disabled: string;
export const label: string;
export const labelInfo: string;
export const helperText: string;
export const primary: string;
export const success: string;
export const warning: string;
export const danger: string;
